### ISSUE TITLE
Using Manifold or core.async

### ISSUE THREAD

**Issue by danielcompton** [apa512/clj-rethinkdb#62]
In developing #55 we need to make a decision whether to use Manifold or core.async for our asynchronous API. We probably want to be able to provide a core.async API anyway as I imagine this will be the most common case, however there are good reasons to use Manifold, namely:

> [It] can be used as a translation layer between libraries which use similar but incompatible abstractions.

What are peoples thoughts on this? I'm not familiar with Manifold. One potential downside is we gain extra dependencies on Riddley. I'm not sure how safe this is, I've had issues with Potemkin in the past.

**Comment by jwr** [comment]
core.async. It's widely used, known, proven to work. No additional dependencies.

clj-rethinkdb is an interface to a database. Much as RethinkDB is exciting, DB drivers should not be too exciting, because my life as an app developer is exciting enough. I'd rather have clj-rethinkdb disappear altogether, because I have enough to worry about (no offense).

**Comment by danielcompton** [comment]
I think at this point we'll stick with core.async. However the door is open in the future to use Manifold as it matures and gains adoption.

**Comment by danielcompton** [comment]
Unless anyone has any really strong feelings the other way, then we can discuss this more.
