### ISSUE TITLE
Not derefing conn atom in send-query

### ISSUE THREAD

**Issue by danielytics** [apa512/clj-rethinkdb#98]
While looking at the code for #97 I noticed that some code in https://github.com/apa512/clj-rethinkdb/blob/master/src/rethinkdb/net.clj#L116-L122 does `(:key conn)` and some does `(:key @conn)`. This _looks_ like a bug?

Unless I'm forgetting something, this should be `@conn` in all cases.

**Comment by danielcompton** [comment]
This looks like a hangover from https://github.com/apa512/clj-rethinkdb/pull/50.

**Comment by danielcompton** [comment]
The code here is correct, but very confusing (as you noticed). It'll be improved to be much less confusing in #51. On this line:

```clj
(swap! (:conn conn) update-in [:waiting] #(conj % token))
```

we want the `conn` field from the Connection record. The `conn` field contains an atom that we mutate. In the other places we are derefing that atom for its values. Because Connection defines it's own deref, `(:waiting @conn)` is equivalent to `(:waiting @(:conn conn))`.
